// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdlggytbewvblqzmogbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbGdneXRiZXd2Ymxxem1vZ2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTEzNDEsImV4cCI6MjA2MDMyNzM0MX0.HBh9hZqIj9458Wm-_L9Nnzir8WmuIgYZqsaWmoLNOVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);